### ISSUE TITLE
Most Death Mountain Caves Unreachable (853305789) (4.3.0 7a7e62d)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#131]
Came in via the Raft, and noticed that I had little access to the caves in Death Mountain.

Flagset: `hEAEiqAFerX2WTVKtVeRf+2csmv@smiyAAWA`
Seed: `853305789`

Red = Inaccessible
Green = Continent Connector

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/a5e8701c-f57c-4159-9542-b5fc5bfc5920)

**Comment by Ellendar** [comment]
Two separate issues here:
1) There was a debug bypass on that was causing seeds that were "close enough" to bypass the reachability logic. Turned that off.
2) For climates that had desert/grave/forest coefficients that were too small, mountain would grow too much relative to the terrain, and the DM would be too constrained to be routeable a large portion of the time. I added in a check that scales the relative growth of different terrain types in DM only based on the aggregate terrain growth relative to mountain, to attempt to normalize the "openness" of climates that would otherwise be more cramped on DM.
