### ISSUE TITLE
Modernizing the Installer/Installation Process

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#162]
Forgive me, as I'm certainly not knowledgeable about installers or the installation process and perhaps being a bit of a pedant, but right now, the installer...
 * Won't run if the same version is already installed, forcing it to be manually uninstalled, resulting in the loss of any saved presets and the ROM's path.<sup>***1***</sup>
 * Doesn't close (or ask to close) any already running randomizer apps that use the same folder when updating through the application itself, resulting in the installation process failing due to the file(s) being in use.
 * Doesn't remember the previously installed path if you don't use the default.
 * Leaves a huge mess of files and folders in the base installation folder.<sup>***2***</sup>
 * Looks and feels dated (e.g. when browsing for a path to install to).

I'm sure updating the installer to be more modern is somewhere on the todo list, but I just wanted to create a ticket documenting some issues I've experienced.

<sup>***1***</sup> I don't know if this is always an issue because normally we're updating right through the program, but...
![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/398d1754-6127-4738-afd3-6eb99f2c5a5a)

<sup>***2***</sup> Perhaps I'm being nitpicky, but there's so much stuff that get installed.  Is all of this necessary?
![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/f4f3fd47-ab79-46d2-8f7a-ef2024a6470f)

**Comment by Ellendar** [comment]
I am incredibly unlikely to change this anytime soon. A large number of these issues are just caused by the process I use to make betas being extremely quick and dirty. Doing the whole process to make a normal release and make it work though the in app update takes a long time and is very fragile. There is no way I'm doing that for beta releases.

I really don't care at all how the installer looks, as it's basically the least important thing in the entire program. Most users are going to only see it once, spam click next until it's installed, and the never care about it again.

The reason it installs so many files is i'm including a lot of the dependencies instead of requiring people download them themselves. I could make it a requirement that people manually download .net runtimes themselves and probably shrink it by 80-90%, but that creates way more likelihood people are going to unsuccessfully install and either give up right away, or need technical support, all to cut the size of the install by like.... 20MB.

I don't like the install process, but all of these things are like... the least important reasons to change it. The most important reason would be able to automatically hook scripts into it do do stuff like update people's saved flags and verify permissions, but reworking it is a lot of work for basically no gain.
