### ISSUE TITLE
Unable to Generate Vanilla/Shuffled Palace Layouts w/o Palace Item Shuffling Enabled (4.3.2)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#179]
The randomizer gets stuck at the "Generating Palaces" step when using `Vanilla` or `Shuffled` palace layouts, _if_ `Shuffle Palace Items` is also not enabled.  Even if you start the game with all palace items, the seed will still not move beyond "Generating Palaces."

**Vanilla Palace Layouts / Palace Item Shuffle DISABLED - Does Not Generate**
`AD+N6Fg!ARFJAAAJCAV5D+@MAhAARAJdAAFRA`
`509137403`

**Vanilla Palace Layouts / Palace Item Shuffle ENABLED - Successful Generation**
`AD+N6Fg!ARFJAAAJCAV5D+@MAhAATAJdAAFRA`
`509137403`

**Comment by Ellendar** [comment]
2 Causes here:
- The safety check for vanilla palace items did not consider downstab/upstab as a western collectable, so the [[UPSTAB, GLOVE],[DOWNSTAB,GLOVE]] room in vanilla 3 was unclearable according to the logic.
- There was a bug in the requirements system where when multiple composite requirements were present they were ANDed rather than ORed.
