### ISSUE TITLE
Carock Can Block Required Progression (4.3.12)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#208]
When `Boss Rooms Exit to Palace` is enabled, Carock can block the required progression items to obtain the Reflect spell, making the seed unable to be completed.

This is more of a reminder to Ellendar than anything else, as he is aware of this and noted that Carock doesn't always appear in "his" boss room.  I believe the fix for this is in place in 4.4, but I'm submitting a ticket as there is to be another 4.3.X build before the tournament begins.

**Comment by Ellendar** [comment]
The 4.4 fix actually wasn't fully implemented, so it's a good thing I looked at it. Backported some fixes to requirements from 4.4, added in a method in Requirements to allow adding a hard requirement to the requirements set, and then made Palaces add a hard requirement of REFLECT to P4's boss room immediately after generating but before any logic is done.

Also ported those updates forward to 4.4 (in a different place because of 4.4's palace generation overhaul) so 4.4 should also now always work correctly.
