### ISSUE TITLE
Desert Tile Overworld -> Side View Connection Incorrect (4.1.2)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#51]
Flags: `hEAK0sALvstUWVXvUtg$o6tFX@4X4yAAjh`
Seed: `106068273`
Hash: `D7RR2P`

This seed was submitted in the Z2R Discord as possibly unbeatable, and looking through the ROM reveals that the Desert Tile on the overworld connects to a swamp encounter.

![image](https://user-images.githubusercontent.com/6069346/234451289-173e4e3e-0293-4fa4-b84a-0415ad21b3e2.png)

This side view screen is actually a standard swamp encounter (from an overworld enemy), but the connection data in the ROM is 26 (Overworld: Desert Tile) to 47 (Side View: Swamp).  The Vanilla ROM shows that 26 should connect to 46, and 46, in both the Vanilla ROM and the randomized ROM, shows that it is the actual Desert Tile.

In the above seed, the Medicine was on the Desert Tile, which was required for Fairy, whereas the Magic Key was located in P2.

![image](https://user-images.githubusercontent.com/6069346/234451443-8caa4ba4-9687-4bfa-b8cc-5576b26f8b15.png)

Two additional notes for the above seed:

1) The Desert Tile is being used as a pass-through, and emulating it after hooking it up properly in the editor (26 > 46) shows the same bad behavior from 4.0.4.  Is the fact that the Desert Tile has ended up at this pass-through location also considered a bug?  **PLEASE SEE ISSUE #52 FOR A POSSIBLE FIX!**

2) There is a pass-through cave located in Death Valley that connects to itself in a loop (19 <-> 20), but the only additional location that is locked in there is a Fence/Wilson encounter.  I know that not every minor location is expected to be accessible, but does this still hold true in a Vanilla Shuffled biome?

![image](https://user-images.githubusercontent.com/6069346/234451625-cd3a6395-e3ac-4d9b-b11e-485d484e20da.png)

**Comment by Ellendar** [comment]
This is a data representation issue. Part of the fix for #2 was manually setting it to load page 1 instead of page 0. The problem is that while z2edit represents page as either the index (0/1/2/3) or the number of pixels from the left edge of the screen (0 / 256 / 512 / 768) the corresponding variable in the rando actually stores the literal value of the left 2 bits of that byte of the location data (0 / 64 / 128 / 192). Since it was being set to 1, that was being bitwise ored onto the byte, incrementing the map number instead, turning the desert tile from map 46 to map 47, which is just a swamp encounter.

Eventually, as part of the effort to stop storing bits on the data objects and push to the rom all at once, this should be changed to have the map page just be 0/1/2/3. For now, I just set it to 64 and it works properly.
