### ISSUE TITLE
"No Duplicate Rooms" Flag Including Duplicate Rooms

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#60]
Mentioned the other day that I noticed 1:1 duplicate rooms being used in palaces when the "No Duplicate Rooms" flag is enabled, so I'm going to dump all the problematic flags/seeds into this thread for review.

Version: `4.1.4 0419d15`
Flags: `AAAJ4AAFeqXtN1TaM0g$8v4BX#4XRx$$sh`
Seed: `900855000`
Hash: `NMMEHC`

### **P4 (West - SW Corner):**
![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/4c6bc540-8def-4ae9-b3d6-6b152e8de6b3)

### **Great Palace (Maze Island):**
![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/fd6d2d94-277e-4d2c-860e-039bc59072eb)

**Comment by Ellendar** [comment]
As usual, this was an embarassingly stupid mistake. There is a validation rule that says no duplicate rooms can only be used in reconstructed palaces when community rooms are on. Otherwise the room pool isn't large enough to safely remove duplicates and still be able to construct palaces.

Unfortunately, that validation rule was triggering if the seed DID use community rooms, instead of DID NOT. So any time you actually turned it on, it turned itself off. This was a fairly late validation rule in development and I just missed it...
