### ISSUE TITLE
Game Locks Up On Palace Room Transition | Incorrect Exit Data (4.2.0 5e2fb95)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#72]
Game locks up when leaving a community item room via the elevator (down) exit.

Flags: `hEAErqAFarXtN1TcDwpozv4SX#4XR7AALy`
Seed: `852352288`
Hash: `388JKO`
Bug in action: https://www.twitch.tv/videos/1855533710?t=0h51m40s
Editor:
![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/13ba8254-799e-4d1e-99aa-bf18627bd891)

**Comment by Ellendar** [comment]
This was a complication of the exit validation. Because this room is segmented, the logic actually treats it as 2 separate rooms, then both rooms are written to the same space in the rom. Previously, each room would overwrite the missing data of the other, and they would merge implicitly, there was an explicit check to not save exits that went outside, which allowed the writes to not interfere with each other, but also broke the validation. When it was removed, the left/right version of the room overwrote the up version of the room, meaning the down exit no longer worked.

The fix was just a check that manually remerges the two rooms together after the logic has been run and the palace generated.
