### ISSUE TITLE
Character Sprites Turn Grayscale When Using The "Default" Normal Tunic Color Under Certain Conditions (4.2.0)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#75]
When a character sprite is set to use the "default" color for the normal tunic, it will turn grayscale, until transitioning screens, after any of the following:

A) A spell, other than Fairy or Shield, is cast.
B) A spell is learned from a town wizard.
C) An item is picked up.
D) A fairy is touched (and heals).

Example (A): https://www.twitch.tv/videos/1859270215?t=0h54m45s
Example (B): https://www.twitch.tv/videos/1859270215?t=0h28m14s
Example (C): https://www.twitch.tv/videos/1859270215?t=0h18m24s
Example (D): https://www.twitch.tv/videos/1859270215?t=0h45m6s

The character sprite does _not_ turn grayscale if you:
A) First cast the Shield spell before engaging in any of the above.
B) Select a color other than "Default" for the normal tunic, even if the color that's chosen matches the default color.

EDIT: This was tested with the following sprites: Link, Black Mage, Fighter, Midna, and Samus*.  However, Samus does not turn completely grayscale, as can be seen in the following image:
![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/ebb5e808-b887-4631-9a04-a76cb39e4dd4)

**Comment by Ellendar** [comment]
Feel free to ignore me assigning this to you, I figure you probably know what's up?

**Comment by Ellendar** [comment]
I'm not sure entirely why this worked, but it did. Something about the change caused the tunic / shield tunic colors to be written, even when they were default. That meant an uninitialized color pallette was being written to the tunic colors, which was then loaded as color 0. I'm not sure why this only kicked in once the palette was reloaded after a spellcast, but it was.

The fix was just initializing c1/c2 to null in the sprite color logic, and only writing them to the rom if they are set either by configuration or random assignment.
