### ISSUE TITLE
Multiples Of The Same Item Being Found (4.2.1)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#79]
Originally reported in 4.2.0, it has shown up again in 4.2.1 with the following seed:

Version: `4.2.1 3f3c979`
Flagset: `AJAN6AAFCWXtN1TbtcY$8vncX#4XznmwJR`
Seed: `804140900`
Hash: `iE4CJ9`
Issue: Boots are available in both Palace 2 (West) and Maze Island.

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/cb1e4a7b-774f-4f66-8e9a-650f6da86621)

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/3f905e21-8569-4c29-b548-05f183d36d83)

**Comment by Ellendar** [comment]
LoadItemLocs() is a dumb method that for sure should only be called once in the generation process, but is being called twice because digshake. After moving palace loading to before item loading, a call to LoadItemLocs() was blanking out ItemLocs in a way that caused 1 location per iteration to remain the same as the item at that location in the previous generation.
