### ISSUE TITLE
Horsehead Stuck in Floor in Community Item Room (4.2.3)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#96]
Version: `4.2.3 da69ef3`
Flagset: `AAAN6AAFesXtN1TeM0g$8v4cX#4XR7AAWR`
Seed: `340633205`
Hash: `HOMVSS`
Room: `P2-17`

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/efa6786d-76e7-4102-ae1f-96becca3c8d6)

**Comment by Ellendar** [comment]
This was being caused by the fix that forces the location of bosses in pool 1 item rooms was updating NewEnemies, but depending on the flags, NewEnemies might not be used, or might not have been initialized yet.

Fix was moving the fix from CreatePalaces where digshake had it to UpdateEnemies where it probably belongs.
