### ISSUE TITLE
Pass-Through Cave Buried in a Mountain (4.2.4)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#99]
One side of a north-south pass-through cave on the East is buried in the mountains that border the Death Valley volcano.

Version: `4.2.4 6933807`
Flagset: `RAAN6AAFesXtN1TeM0g$8v4cX#4XR7AALh`
Seed: `281950022`
Hash: `K0PRFH`
Video: https://www.twitch.tv/videos/1888728410?t=3h12m27s

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/b2c5b275-843f-45c0-afcc-384d2bc3a0e5)

**Comment by Ellendar** [comment]
Volcano was being drawn AFTER other caves were drawn, and after random terrain was created. The volcano cave placement did not check for adjacent locations, so it would overwrite the existing cave when it drew its perimeter mountains. This is technically a 4.0.4 issue, but in 4.0.4, all transit caves are required to be accessible, so anytime this happen it would be thrown out during IsEverythingAccessible(). Because pointless caves are allowed in 4.2, this was able to happen. 

The fix was to just draw the volcano before the caves so the cave validation will avoid this. This _probably_ won't cause issues with other terrain generation.... ...
